### ISSUE TITLE
能说明一下怎么用的么？

### ISSUE THREAD

**Issue by quhw** [Yoshi2889/b250m-opencore-config#1]

**Comment by NanoSector** [comment]
Hi,

I do not speak Chinese, but your question seems to translate to “how do I use this?”

This repo isn’t meant as a guide of any sorts. There are some good OpenCore guides on the internet and I don’t wish to compete with those. It is merely a reference for myself and possibly others to set up a system similar to mine. If you’re familiar with OpenCore you should be able to use this repo and adapt the configuration to your specific needs.

**Comment by quhw** [comment]
Thanks, I finally have solved all problems. It seems working pretty well.
